# Build for Markturn
version: 2.1

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"

jobs:
  build:
    docker:
      - image: srg97/markturn_ubuntu
    steps:
      - greeting:
          to: "Stephan"
      - checkout
      - run: apt update
      - run: mkdir build
      - run: cd build && cmake -DLINK_STATIC=0FF -DCMAKE_BUILD_TYPE=Release .. -G Ninja
      - run: cd build && ninja && ninja install && ldconfig
      - run: cd build && ctest
      - run: cd build && cpack -G DEB
      - store_artifacts:
          path: build/markturn-0.0.0-Linux.deb
      - store_test_results:
          path: test-results
