# Build for Markturn
version: 2.1

jobs:
  build:
    docker:
      - image: srg97/markturn_ubuntu
    steps:
      - restore_cache: 
          key: source-v1-{{ .Branch }}-{{ .Revision }}
      - run:
          name: "Greeting"
          command: echo Hello $CIRCLE_USERNAME
      - run:
          name: "I am on branch"
          command: echo $CIRCLE_BRANCH
      - checkout
      - run: apt update
      - run: mkdir build
      - run: cd build && cmake -DLINK_STATIC=0FF -DCMAKE_BUILD_TYPE=Release .. -G Ninja
      - run: cd build && ninja && ninja install && ldconfig
      - run: cd build && ctest -T Test
      - run: cd build && cpack -G DEB
      - store_test_results:
          path: /root/project/build
      - store_artifacts:
          path: build/markturn-0.0.0-Linux.deb
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"


